name: Build package
on:
  push:
    tags:
      - '*'
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:
  workflow_call:

jobs:

  flatpak:
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-43
      options: --privileged
    steps:
    - uses: actions/checkout@v3
    - uses: flatpak/flatpak-github-actions/flatpak-builder@v6.1
      with:
        bundle: emote.flatpak
        manifest-path: com.tomjwatson.Emote.yml
        cache-key: flatpak-builder-${{ github.sha }}

  snap:
    runs-on: ubuntu-latest
    outputs:
      snap-file: ${{ steps.build-snap.outputs.snap }}
    steps:
    - uses: actions/checkout@v3

    - uses: snapcore/action-build@v1
      id: build-snap

    - run: |
        sudo snap install --dangerous ${{ steps.build-snap.outputs.snap }}

    - run: |
        emote --version

    - uses: actions/upload-artifact@v3
      with:
        name: emote-pkg
        path: ${{ steps.build-snap.outputs.snap }}

#   publish:
#     if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/')
#     runs-on: ubuntu-latest
#     needs: build
#     steps:
#     - uses: actions/download-artifact@v3
#       with:
#         name: gbeuzeboc-snapped-ros2-pkg
#         path: .
#     - uses: snapcore/action-publish@v1
#       env:
#         SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.STORE_LOGIN }}
#       with:
#         snap: ${{needs.build.outputs.snap-file}}
#         release: ${{ startsWith(github.ref, 'refs/tags/') && 'candidate' || 'edge'}}